{
 "title": "TDC Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requisições 2xx",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_responseTime_count{statusCode=\"200\"}[$__rate_interval])) by (field)",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Requisições 5xx",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_responseTime_count{statusCode=\"500\"}[$__rate_interval])) by (field)",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Requisições 200 x 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(le, field, statusCode) (rate(http_server_responseTime_count[10m]))",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, field) (rate(http_server_responseTime_bucket[10m])))",
     "legendFormat": "{{field}}"
    }
   ]
  }
 ]
}